import SessionProvider from '@/components/SessionProvider'

import { getServerSession } from 'next-auth'

import SideBar from '@/components/SideBar'
import '@/styles/globals.css'
import { authOptions } from '../pages/api/auth/[...nextauth]'
import Login from '@/components/Login'
import ClientProvider from '@/components/ClientProvider'

export const metadata = {
  title: 'ChatGPT-Messager',
  description: 'Generated by Next.js'
}

// 服务器组件 可以 async
export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const session = await getServerSession(authOptions)
  return (
    <html lang='en'>
      <body>
        <SessionProvider seesion={session}>
          {!session ? (
            <Login />
          ) : (
            <div className='flex'>
              {/* 侧边栏 */}

              <div className='bg-[#202123] max-w-xs h-screen overflow-auto  md:min-w-[16rem]'>
                <SideBar></SideBar>
              </div>

              {/* ClientProvider - 消息通知 */}
              <ClientProvider></ClientProvider>

              <div className='bg-[#343541] flex-1'>{children}</div>
            </div>
          )}
        </SessionProvider>
      </body>
    </html>
  )
}
