import SideBar from '@/components/SideBar'
import '@/styles/globals.css'

export const metadata = {
  title: 'ChatGPT-Messager',
  description: 'Generated by Next.js'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body>
        <div className='flex'>
          {/* 侧边栏 */}

          <div className='bg-[#202123] max-w-xs h-screen overflow-auto md:min-w-[20rem]'>
            <SideBar></SideBar>
          </div>

          {/* ClientProvider - 消息通知 */}

          <div className='bg-[#343541] flex-1'>{children}</div>
        </div>
      </body>
    </html>
  )
}
